//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stored_Procedure_Manager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServerNameString {
            get {
                return ((string)(this["ServerNameString"]));
            }
            set {
                this["ServerNameString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InstanceString {
            get {
                return ((string)(this["InstanceString"]));
            }
            set {
                this["InstanceString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DatabaseString {
            get {
                return ((string)(this["DatabaseString"]));
            }
            set {
                this["DatabaseString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserNameString {
            get {
                return ((string)(this["UserNameString"]));
            }
            set {
                this["UserNameString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PasswordString {
            get {
                return ((string)(this["PasswordString"]));
            }
            set {
                this["PasswordString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string PassFailString {
            get {
                return ((string)(this["PassFailString"]));
            }
            set {
                this["PassFailString"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Sierra Workforce Solutions\\Automation Manager\\Installers")]
        public string InstallerFolderString {
            get {
                return ((string)(this["InstallerFolderString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("scsint")]
        public string PasswordOk {
            get {
                return ((string)(this["PasswordOk"]));
            }
            set {
                this["PasswordOk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EXE1checkBoxString {
            get {
                return ((bool)(this["EXE1checkBoxString"]));
            }
            set {
                this["EXE1checkBoxString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EXE2checkBoxString {
            get {
                return ((bool)(this["EXE2checkBoxString"]));
            }
            set {
                this["EXE2checkBoxString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EXE3checkBoxString {
            get {
                return ((bool)(this["EXE3checkBoxString"]));
            }
            set {
                this["EXE3checkBoxString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EXE4checkBoxString {
            get {
                return ((bool)(this["EXE4checkBoxString"]));
            }
            set {
                this["EXE4checkBoxString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EXE5checkBoxString {
            get {
                return ((bool)(this["EXE5checkBoxString"]));
            }
            set {
                this["EXE5checkBoxString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EXE6checkBoxString {
            get {
                return ((bool)(this["EXE6checkBoxString"]));
            }
            set {
                this["EXE6checkBoxString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EXE7checkBoxString {
            get {
                return ((bool)(this["EXE7checkBoxString"]));
            }
            set {
                this["EXE7checkBoxString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EXE8checkBoxString {
            get {
                return ((bool)(this["EXE8checkBoxString"]));
            }
            set {
                this["EXE8checkBoxString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EXE9checkBoxString {
            get {
                return ((bool)(this["EXE9checkBoxString"]));
            }
            set {
                this["EXE9checkBoxString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EXE10checkBoxString {
            get {
                return ((bool)(this["EXE10checkBoxString"]));
            }
            set {
                this["EXE10checkBoxString"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter the name you would like this button to have.")]
        public string InfoTextBoxButtonNameString {
            get {
                return ((string)(this["InfoTextBoxButtonNameString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter the name of the Stored Procedure that you want the button to execute.")]
        public string InfoTextBoxSPNameString {
            get {
                return ((string)(this["InfoTextBoxSPNameString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActivationPass {
            get {
                return ((string)(this["ActivationPass"]));
            }
            set {
                this["ActivationPass"] = value;
            }
        }
    }
}
